const productList = [
  {
    multilingual: [],
    volumeBasedPrices: [],
    createdAt: "2020-07-12T13:04:28.000Z",
    updatedAt: "2022-06-29T05:59:49.000Z",
    deletedAt: null,
    id: 1,
    name: "Aata Sunridge - 10.KG x1",
    sku: "Retailo-13-000001",
    imageUrl: null,
    description: "",
    stockQuantity: 217600,
    weight: 0,
    length: 0,
    width: 0,
    height: 0,
    price: 1000,
    costPrice: 2500,
    mrp: 1000,
    tradePrice: null,
    size: "",
    unit: "",
    brand: "Sunridge",
    urduName: "Aata Sunridge - 10.KG x1",
    urduUnit: "",
    urduSize: "",
    urduBrand: "",
    disabled: false,
    deletedBy: null,
    updatedBy: 160,
    barcode: "HYPR473455395",
    consentRequired: false,
    locationId: 13,
    taxInclusive: true,
    taxPercent: 10,
    taxCategory: 2,
    deliveryTime: null,
    quantityLimit: null,
    isDynamicPriceEnabled: false,
    isVolumeBasedPriceEnabled: false,
    physicalStock: 56,
  },
  {
    multilingual: [],
    volumeBasedPrices: [],
    createdAt: "2020-07-12T13:04:28.000Z",
    updatedAt: "2022-06-29T05:59:49.000Z",
    deletedAt: null,
    id: 2,
    name: "Aata Sunridge - 10.KG x1",
    sku: "Retailo-13-000002",
    imageUrl: null,
    description: "",
    stockQuantity: 217600,
    weight: 0,
    length: 0,
    width: 0,
    height: 0,
    price: 2000,
    costPrice: 2500,
    mrp: 1000,
    tradePrice: null,
    size: "",
    unit: "",
    brand: "Sunridge",
    urduName: "Aata Sunridge - 10.KG x1",
    urduUnit: "",
    urduSize: "",
    urduBrand: "",
    disabled: false,
    deletedBy: null,
    updatedBy: 160,
    barcode: "HYPR473455395",
    consentRequired: false,
    locationId: 13,
    taxInclusive: true,
    taxPercent: 10,
    taxCategory: 2,
    deliveryTime: null,
    quantityLimit: null,
    isDynamicPriceEnabled: false,
    isVolumeBasedPriceEnabled: false,
    physicalStock: 56,
  },
  {
    multilingual: [],
    volumeBasedPrices: [],
    createdAt: "2020-07-12T13:04:28.000Z",
    updatedAt: "2022-06-29T05:59:49.000Z",
    deletedAt: null,
    id: 3,
    name: "Aata Sunridge - 10.KG x1",
    sku: "Retailo-13-000003",
    imageUrl: null,
    description: "",
    stockQuantity: 217600,
    weight: 0,
    length: 0,
    width: 0,
    height: 0,
    price: 3000,
    costPrice: 2500,
    mrp: 1000,
    tradePrice: null,
    size: "",
    unit: "",
    brand: "Sunridge",
    urduName: "Aata Sunridge - 10.KG x1",
    urduUnit: "",
    urduSize: "",
    urduBrand: "",
    disabled: false,
    deletedBy: null,
    updatedBy: 160,
    barcode: "HYPR473455395",
    consentRequired: false,
    locationId: 13,
    taxInclusive: true,
    taxPercent: 10,
    taxCategory: 2,
    deliveryTime: null,
    quantityLimit: null,
    isDynamicPriceEnabled: false,
    isVolumeBasedPriceEnabled: false,
    physicalStock: 56,
  }
]


module.exports = {
  productList,
};
