const KYCs = {
  SHOP_ADDRESS: 17,
  SHOP_PICTURE: 59,
  DISCOUNTS_OFFERED: 67,
  MONTHLY_PURCHASES: 70,
  SHOP_NAME: 16,
  UNIQUE_SKU_BOUGHT: 69,
  FULL_NAME: 4,
  MONTHS_ACTIVE: 71,
  LOCATION_PIN: 66,
  NO_OF_OWNERS: 18,
  WEEKLY_PURCHASES: 68,
  AVERAGE_BASKET_3_MONTHS: 65,
};

module.exports = {
  KYCs,
};
