version: "3.7"
services:
  redis-server:
    image: "redis:alpine"
    container_name: ${REDIS_CONTAINER_NAME}-test
    hostname: redis-server
    command: ["redis-server", "--notify-keyspace-events", "Egx"]
    ports:
      - "1234:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - ${SERVICE_NETWORK_NAME}-test
  db:
    container_name: ${DB_CONTAINER_NAME}-test
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - ${SERVICE_NETWORK_NAME}-test
    expose:
      - "3306"
    ports:
      - "3306:3306"    
    environment:
      - MYSQL_ROOT_PASSWORD=${TEST_DB_PASSWORD}
      - MYSQL_DATABASE=${TEST_DB_NAME}
      - MYSQL_USER=${TEST_DB_USER}
      - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
      - MYSQL_HOST=${TEST_DB_ADDRESS}

  hypr_backend:
    build:
      context: .
      args:
        GL_NPM_TOKEN: ${GL_NPM_TOKEN}
    command:
      [
        "bash",
        "-c",
        "npm ci && npm run test:e2e",
      ]
    env_file:
      - .env
    environment:
      - NODE_ENV=test
      - DB_HOST=${TEST_DB_ADDRESS}
      - DB_ADDRESS=${TEST_DB_ADDRESS}
      - DB_USER=${TEST_DB_USER}
      - DB_PASSWORD=${TEST_DB_PASSWORD}
      - DB_NAME=${TEST_DB_NAME}
    container_name: ${SERVICE_CONTAINER_NAME}-test
    ports:
      - "8090:8090"
    volumes:
      - .:/sails/
      - /sails/node_modules
    networks:
      - ${SERVICE_NETWORK_NAME}-test
    links:
      - redis-server
    depends_on:
      - redis-server
      - db
networks:
  hypr-network-test:    
    driver: bridge